/**
 * Data access layer.
 * Reads pre-fetched JSON files from src/data/ (generated by scripts/fetch-data.mjs).
 * No runtime network calls — works offline and inside Docker.
 */
import lessonsData from '../data/lessons.json';
import vocabData from '../data/vocabulary.json';
import grammarData from '../data/grammar.json';
import kanjiData from '../data/kanji.json';

type Lesson = {
  id: string; title: string; content: string; tags: string[]; lesson_date: string; level: string;
};

type Vocab = {
  id: number; lesson_id: string; kanji: string | null; hiragana: string; romaji: string | null; french: string;
};

type Grammar = {
  id: number; lesson_id: string; pattern: string; explanation: string;
  example_jp: string | null; example_fr: string | null;
};

type Kanji = {
  id: number; character: string; onyomi: string; kunyomi: string;
  meaning_fr: string; example_word: string; example_reading: string; tags: string[];
};

const lessons = lessonsData as Lesson[];
const vocab = vocabData as Vocab[];
const grammar = grammarData as Grammar[];
const kanji = kanjiData as Kanji[];

export function getLessons() {
  return lessons;
}

export function getLesson(id: string) {
  return lessons.find(l => l.id === id) || null;
}

export function getVocab(lessonId?: string) {
  if (lessonId) return vocab.filter(v => v.lesson_id === lessonId);
  return vocab;
}

export function getGrammar(lessonId?: string) {
  if (lessonId) return grammar.filter(g => g.lesson_id === lessonId);
  return grammar;
}

export function getKanji() {
  return kanji;
}
